[project]
name = "global-client"
authors = ["IoT Solutions Team"]
description = "Decentralized IoT node management and global client tracking system"
telemetry = false
requirements = []
[contracts.global-governance]
path = "contracts/global-governance.clar"
depends_on = []

[contracts.client-verification]
path = "contracts/client-verification.clar"
depends_on = []

[contracts.client-registry]
path = "contracts/client-registry.clar"
depends_on = []

[contracts.client-rewards]
path = "contracts/client-rewards.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
